name: eRNAi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pandas
  - pytest
  - snakemake
  - biopython
  - pip=23.3.1
   - pip:
    - numpy==1.26
    - pandas==2.1.1
    - scipy==1.11.3

 
