##### directories
result_dir: "results/"

##### input_files
taxid: 9031

#### files
sra:
  sra_id: "SRR8265535"
  paired: True
  thread: 8 

algorithm: "kraken2"  # Используемый алгоритм
database: "kraken2_db"  # Путь к базе данных Kraken2 
input:
  - "results/output/SRR8265535_filtered_1.fastq"  # Путь к первому файлу с ридами (R1)
  - "results/output/SRR8265535_filtered_2.fastq"  # Путь ко второму файлу с ридами (R2)
output_dir: "results/output"  # Директория для выходных файлов
sample_name: "sample1"  # Имя образца (используется для именования выходных файлов)

##### params for specific rules ####
fastp:
    thread: 8
    qualified_quality_phred: 20
    min_length: 50
    detect_adapters: True

# metaphlan parameters
metaphlan:
  threads: 8

# humann parameters
humann:
  threads: 8

# входные файлы
metagenome: "metagenome.fastq.gz"
host_genome: "host_genome.fna"  # референс

output_dir: "results/output"  # результаты
