##### directories
output_dir: "results/output"  # результаты работы программ

##### input_files
taxid: 97693

#### for pre-files
sra:
  sra_id: ['SRR26990492',
  'SRR26990493',
  'SRR26990494',
  'SRR26990503',
  'SRR26990504',
  'SRR26990505',
  'SRR26990506',
  'SRR26990507',
  'SRR26990508']
  
  paired: True
  thread: 4

kallisto:
  kmer_size: 31  # Длина k-mer (по умолчанию 31)
  bootstrap: 30  # Количество бутстрап-повторов для оценки неопределённости

algorithm: "kraken2"  # Используемый алгоритм
database: "kraken2_db"  # Путь к базе данных Kraken2 
#input:
#  - "results/output/{sra.sra_id}_filtered_1.fastq"  # Путь к первому файлу с ридами (R1)
#  - "results/output/{sra.sra_id}_filtered_2.fastq"  # Путь ко второму файлу с ридами (R2)
output_dir: "results/output"  # Директория для выходных файлов
sample_name: "sample1"  # Имя образца (используется для именования выходных файлов)

##### params for specific rules ####
fastp:
    thread: 8
    qualified_quality_phred: 20
    min_length: 50
    detect_adapters: True

# metaphlan parameters
metaphlan:
  threads: 8
# bracken parameters
read_length: 150
taxonomic_level: ['S','G', 'P']

# humann parameters
humann:
  threads: 8

# входные файлы
metagenome: "metagenome.fastq.gz"
host_genome: "host_genome.fna"  # референс

