##### directories
output_dir: "results/ourput"  # результаты работы программ

##### input_files
taxid: 9031

#### for pre-files
sra:
  sra_id: ['SRR27593613',
  'SRR27593614',
  'SRR27593615',
  'SRR27593623',
  'SRR27593624',
  'SRR27593625']
  paired: True
  thread: 4

kallisto:
  kmer_size: 31  # Длина k-mer (по умолчанию 31)
  bootstrap: 30  # Количество бутстрап-повторов для оценки неопределённости

algorithm: "kraken2"  # Используемый алгоритм
database: "kraken2_db"  # Путь к базе данных Kraken2 
input:
  - "results/output/{sra_id}_filtered_1.fastq"  # Путь к первому файлу с ридами (R1)
  - "results/output/{sra_id}_filtered_2.fastq"  # Путь ко второму файлу с ридами (R2)
output_dir: "results/output"  # Директория для выходных файлов
sample_name: "sample1"  # Имя образца (используется для именования выходных файлов)

##### params for specific rules ####
fastp:
    thread: 8
    qualified_quality_phred: 20
    min_length: 50
    detect_adapters: True

# metaphlan parameters
metaphlan:
  threads: 8

# humann parameters
humann:
  threads: 8

# входные файлы
metagenome: "metagenome.fastq.gz"
host_genome: "host_genome.fna"  # референс

