##### directories
result_dir: "results/"

##### input_files
taxid: 6239

#### files
sra:
  sra_id: "SRR13239754"  # Идентификатор SRA 
  thread: 8  

##### params for specific rules ####
fastp:
  qualified_quality_phred=30,
  length_required=50,
  threads=6,
  min_length=50,
  detect_adapters="--detect_adapter_for_pe"

# metaphlan parameters
metaphlan:
  threads: 8

# humann parameters
humann:
  threads: 8

# входные файлы
metagenome: "metagenome.fastq.gz"
host_genome: "host_genome.fna"  # референс

output_dir: "results/output"  # результаты
