# paths
output_dir: "kraken"
input_dir: "kraken"                    
ref_dir: "data/data_ggallus/genome"
taxid: "galGal6"
sample_name: "gallus_gallus"     
accession: "GCF_000002315.6"      

sra:
  sra_id:
    - "SRR8265535"
    - "SRR8265537"
    - "SRR8265543"
    - "SRR8265545"
    - "SRR8265547"
    - "SRR8265551"
    - "SRR8265564"
    - "SRR8265565"
    - "SRR8265567"
    - "SRR8265569"
    - "SRR8265571"
    - "SRR8265536"
    - "SRR8265538"
    - "SRR8265544"
    - "SRR8265546"
    - "SRR8265552"
    - "SRR8265563"
    - "SRR8265566"
    - "SRR8265568"
  paired: True
  thread: 2

threads:
  bwa_index: 8
  bwa_align: 8
  sam_to_bam: 8
  split_reads: 4

# transcriptome params
#==================
kallisto:
  kmer_size: 31   # k-mer length (default is 31)
  bootstrap: 30   # Number of bootstrap replicates for uncertainty estimation

#kraken2 params
#============================
algorithm: "kraken2"                       # Algorithm to be used
database: "/nfs/home/vishtuganova/kraken2_db"    

#============================
# bracken params
read_length: 150
taxonomic_level: ['S']

# preprocessing params
#=================
fastp:
    thread: 8
    qualified_quality_phred: 20
    min_length: 50
    detect_adapters: True

# metaphlan params
#===============================
metaphlan:
  threads: 8

# humann params
#===============================
humann:
  threads: 8